version: '3.8'
services:
  web:
    image: ghcr.io/luoibac.studio:latest
    env_file:
      - ../.env.production
    depends_on:
      - db

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:15-alpine
    env_file:
      - ../.env.production
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  static_volume:
  db_data:
